package com.tej.project.model;
// Generated 5 Oct, 2018 5:05:32 AM by Hibernate Tools 4.3.1



/**
 * Employees generated by hbm2java
 */
public class Employees  implements java.io.Serializable {


     private int id;
     private String fname;
     private String lname;
     private String designation;
     private String pay;
     private String department;

    public Employees() {
    }

    public Employees(int id, String fname, String lname, String designation, String pay, String department) {
       this.id = id;
       this.fname = fname;
       this.lname = lname;
       this.designation = designation;
       this.pay = pay;
       this.department = department;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }
    public String getDesignation() {
        return this.designation;
    }
    
    public void setDesignation(String designation) {
        this.designation = designation;
    }
    public String getPay() {
        return this.pay;
    }
    
    public void setPay(String pay) {
        this.pay = pay;
    }
    public String getDepartment() {
        return this.department;
    }
    
    public void setDepartment(String department) {
        this.department = department;
    }




}


